name: Build and Attach to Release

on:
  release:
    types: [created]

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create ZIP archive
        run: |
          cd dist
          zip -r ../dist.zip .
          cd ..

      - name: Attach ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: wer-regiert-in.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
